version: '3'
services:
  dotnet-webapi:
    build: .
    ports:
      - "0.0.0.0:8085:80"


# docker run -i -t -p 8082:5000 8082:5000 aspnetapp


// This step should not normally be used in your script. Consult the inline help for details.
withDockerContainer('webapplication2_dotnet-webapi') {
    // some block
}

withDockerServer([uri: 'localhost:7235']) {
    // some block
}


dockerNode(dockerHost: 'localhost:1711', image: 'weba') {
    // some block
}